### ISSUE TITLE
Departure Monitor zeigt die Abfahrten von morgen nicht

### ISSUE THREAD

**Issue by leodlpy7** [fscs/fscs-monitor#19]
![IMG_20240219_233634325](https://github.com/fscs/fscs-monitor/assets/143642143/6726e3ce-2ed8-4ac1-ba6f-9a0923a1dc04)

**Comment by MarchCraft** [comment]
Should be fixed now. Our guess is that the GitHub action was causing that issue. It deployed to the page on PR's aswell as on commits. Should be fixed now(You may need to restart the raspi just unplug and plug back in). Reopen if it still happens.
